# Generated by Django 4.1 on 2024-02-27 14:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("api", "0117_auto_20240220_1702"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "invoice_id",
                    models.CharField(
                        help_text="Stripe Invoice ID", max_length=255, unique=True
                    ),
                ),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_remaining",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("due_date", models.DateTimeField()),
                ("hosted_invoice_url", models.URLField()),
                ("invoice_pdf", models.URLField()),
                ("metadata", models.JSONField()),
                ("number", models.CharField(max_length=255)),
                ("paid", models.BooleanField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                            ("uncollectible", "Uncollectible"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "user_address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.useraddress",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
