# Generated by Django 4.1 on 2024-02-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="hosted_invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="invoice_pdf",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
