# Generated by Django 4.2.17 on 2025-01-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_created_by_invoice_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='check_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
