# Generated by Django 4.2.17 on 2025-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_check_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='check_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
