# Generated by Django 4.2.11 on 2024-06-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0002_paymentmethod_created_by_paymentmethod_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
