# Generated by Django 4.2.13 on 2024-10-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_user_apollo_id_user_apollo_user_id_user_stage'),
        ('payment_methods', '0003_paymentmethod_active_paymentmethod_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.usergroup'),
        ),
    ]
