# Generated by Django 4.1 on 2024-03-07 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0119_useraddress_default_payment_method"),
        ("payment_methods", "0003_alter_paymentmethoduser_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentmethoduser",
            unique_together={("payment_method", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethoduseraddress",
            unique_together={("payment_method", "user_address")},
        ),
    ]
