# Generated by Django 4.2.13 on 2024-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PricingLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(max_length=255, null=True)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricingLineItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
