# Generated by Django 4.1 on 2024-06-19 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_payout_lob_check_id"),
        ("asset_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assethours",
            options={
                "verbose_name": "Asset Hours",
                "verbose_name_plural": "Asset Hours",
            },
        ),
        migrations.AddField(
            model_name="assetmodel",
            name="main_product",
            field=models.ForeignKey(
                default="8b9e813d-be03-4243-87c2-7e6f757f869d",
                on_delete=django.db.models.deletion.PROTECT,
                to="api.mainproduct",
            ),
            preserve_default=False,
        ),
    ]
