# Generated by Django 4.2.13 on 2025-01-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_ordertransferfee_orderpermitfee_ordermaterialfee_and_more'),
        ('asset_management', '0003_remove_asset_main_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='seller_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocation'),
        ),
    ]
