# Generated by Django 4.2.11 on 2024-04-12 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0123_user_type"),
        ("admin_approvals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group_admin_approval_user_invites",
                to="api.user",
            ),
            preserve_default=False,
        ),
    ]
