# Generated by Django 4.1 on 2024-04-27 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_approvals", "0001_initial"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group_admin_approval_user_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="user_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group_admin_approval_user_invites",
                to="api.usergroup",
            ),
        ),
        migrations.AddField(
            model_name="usergroupadminapprovalorder",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_group_admin_approval_order",
                to="api.order",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usergroupadminapprovaluserinvite",
            unique_together={("user_group", "email")},
        ),
    ]
