# Generated by Django 4.1 on 2024-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergroupadminapprovalorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usergroupadminapprovaluserinvite",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
