# Generated by Django 4.2.11 on 2024-04-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_approvals', '0002_usergroupadminapprovaluserinvite_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergroupadminapprovalorder',
            options={'verbose_name': 'Order Approval', 'verbose_name_plural': 'Order Approvals'},
        ),
        migrations.AlterModelOptions(
            name='usergroupadminapprovaluserinvite',
            options={'verbose_name': 'User Invite Approval', 'verbose_name_plural': 'User Invite Approvals'},
        ),
    ]
