# Generated by Django 4.1 on 2024-05-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_approvals", "0003_usergroupadminapprovalorder_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("BILLING", "Billing Manager"),
                    ("MEMBER", "Member"),
                ],
                default="ADMIN",
                max_length=255,
            ),
        ),
    ]
