# Generated by Django 4.2.11 on 2024-04-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_approvals', '0002_alter_usergroupadminapprovalorder_status_and_more'),
        ('admin_approvals', '0003_alter_usergroupadminapprovalorder_options_and_more'),
    ]

    operations = [
    ]
