# Generated by Django 4.1 on 2024-06-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_approvals", "0005_alter_usergroupadminapprovaluserinvite_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="first_name",
            field=models.CharField(default="Test", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usergroupadminapprovaluserinvite",
            name="last_name",
            field=models.CharField(default="Test", max_length=255),
            preserve_default=False,
        ),
    ]
