# Generated by Django 4.2.13 on 2024-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_approvals', '0006_usergroupadminapprovaluserinvite_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupadminapprovaluserinvite',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='URL to redirect to after Auth0 login (defaults to webapp settings.BASE_URL).', max_length=255, null=True),
        ),
    ]
