# Generated by Django 4.2.13 on 2024-11-29 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_approvals', '0007_usergroupadminapprovaluserinvite_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupadminapprovaluserinvite',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
