# Generated by Django 4.2.13 on 2024-12-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_approvals', '0008_usergroupadminapprovaluserinvite_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroupadminapprovaluserinvite',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
