# Generated by Django 4.1 on 2024-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admin_policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usergrouppolicyinvitationapproval",
            name="user_type",
            field=models.CharField(
                choices=[("BILLING", "Billing Manager"), ("MEMBER", "Member")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="usergrouppolicypurchaseapproval",
            name="user_type",
            field=models.CharField(
                choices=[("BILLING", "Billing Manager"), ("MEMBER", "Member")],
                max_length=255,
            ),
        ),
    ]
