# Generated by Django 4.2.11 on 2024-04-26 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0125_merge_20240424_1226'),
        ('admin_policies', '0003_alter_usergrouppolicypurchaseapproval_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergrouppolicyinvitationapproval',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_invitation_approvals', to='api.usergroup'),
        ),
        migrations.AlterField(
            model_name='usergrouppolicymonthlylimit',
            name='user_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy_monthly_limit', to='api.usergroup'),
        ),
        migrations.AlterField(
            model_name='usergrouppolicypurchaseapproval',
            name='user_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_purchase_approvals', to='api.usergroup'),
        ),
    ]
