# Generated by Django 4.1 on 2024-04-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("external_contracts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcontract",
            name="interested_in_loa",
            field=models.BooleanField(default=False),
        ),
    ]
