# Generated by Django 4.1.1 on 2023-02-14 03:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_slot', models.CharField(blank=True, choices=[('4am-8am', '4am-8am'), ('8am-12pm', '8am-12pm'), ('12pm-4pm', '12pm-4pm'), ('4pm-8pm', '4pm-8pm'), ('8pm-12am', '8pm-12am')], max_length=255, null=True)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('additional_schedule_details', models.TextField(blank=True, null=True)),
                ('access_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetailsLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('stripe_invoice_line_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.orderdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Landfill', 'Landfill'), ('MRF', 'MRF'), ('Industrial', 'Industrial'), ('Scrap yard', 'Scrap yard'), ('Compost facility', 'Compost facility'), ('Processor', 'Processor'), ('Paint recycler', 'Paint recycler'), ('Tires', 'Tires'), ('Other recycler', 'Other recycler'), ('Roll-off', 'Roll-off'), ('Mover', 'Mover'), ('Junk', 'Junk'), ('Delivery', 'Delivery'), ('Broker', 'Broker'), ('Equipment', 'Equipment')], max_length=255, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('Services', 'Services'), ('Disposal site', 'Disposal site')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('Inactive', 'Inactive'), ('Inactive - Onboarding', 'Inactive - Onboarding'), ('Inactive - Pending approval', 'Inactive - Pending approval'), ('Active - under review', 'Active - under review'), ('Active', 'Active')], max_length=255, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=255, null=True)),
                ('type_display', models.CharField(blank=True, choices=[('Landfill', 'Landfill'), ('MRF', 'MRF'), ('Industrial', 'Industrial'), ('Scrap yard', 'Scrap yard'), ('Compost facility', 'Compost facility'), ('Processor', 'Processor'), ('Paint recycler', 'Paint recycler'), ('Tires', 'Tires'), ('Other recycler', 'Other recycler'), ('Roll-off', 'Roll-off'), ('Mover', 'Mover'), ('Junk', 'Junk'), ('Delivery', 'Delivery'), ('Broker', 'Broker'), ('Equipment', 'Equipment')], max_length=255, null=True)),
                ('stripe_connect_id', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('marketplace_display_name', models.CharField(blank=True, max_length=20, null=True)),
                ('open_days', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=4099, null=True)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('lead_time_hrs', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('announcement', models.TextField(blank=True, null=True)),
                ('live_menu_is_active', models.BooleanField(default=False)),
                ('location_logo_url', models.URLField(blank=True, null=True)),
                ('downstream_insurance_requirements_met', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, choices=[('New', 'New'), ('Pro', 'Pro'), ('Platinum', 'Platinum')], max_length=255, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('tire_recycler_cert_registration_id_co', models.CharField(blank=True, max_length=100, null=True)),
                ('composting_classification', models.CharField(blank=True, max_length=100, null=True)),
                ('max_paint_gallons_accepted', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('recycling_disposal_classification', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('stripe_customer_id', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('street', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=40, null=True)),
                ('state', models.CharField(blank=True, max_length=80, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=80, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='accountcontactrelation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='master_record',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='property',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='reports_to',
        ),
        migrations.RemoveField(
            model_name='disposalfee',
            name='account',
        ),
        migrations.RemoveField(
            model_name='disposalfee',
            name='location_zone',
        ),
        migrations.RemoveField(
            model_name='disposalfee',
            name='waste_type',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='main_product',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='pricebook',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='product',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='postalcode',
            name='location_zone',
        ),
        migrations.RemoveField(
            model_name='pricebookentry',
            name='pricebook',
        ),
        migrations.RemoveField(
            model_name='pricebookentry',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellerproductlocationzone',
            name='location_zone',
        ),
        migrations.RemoveField(
            model_name='sellerproductlocationzone',
            name='seller_product',
        ),
        migrations.RemoveField(
            model_name='addon',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='addonchoice',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='mainproduct',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='mainproductcategory',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='mainproductcategoryinfo',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='mainproductwastetype',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='access_schedule_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='account',
        ),
        migrations.RemoveField(
            model_name='order',
            name='activated_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='additional_schedule_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_geocode_accuracy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_authorized_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_reduction_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='original_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pricebook',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scheduled_time_slot',
        ),
        migrations.RemoveField(
            model_name='order',
            name='scrap_task_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_geocode_accuracy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_latitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_postal_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_street',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_date_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='family',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_quantity_installments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='number_of_revenue_installments',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_installment_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_schedule_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_unit_of_measure',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revenue_installment_period',
        ),
        migrations.RemoveField(
            model_name='product',
            name='revenue_schedule_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_keeping_unit',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='main_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory'),
        ),
        migrations.AddField(
            model_name='mainproductcategoryinfo',
            name='main_product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory'),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='add_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='ar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='cubic_yards',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='image_del',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='included_rate_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='included_tonnage_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='max_tonnage_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='price_per_additional_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='add_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wastetype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hauler_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='add_on_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addonchoice'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='AccountContactRelation',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='DisposalFee',
        ),
        migrations.DeleteModel(
            name='LocationZone',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='PostalCode',
        ),
        migrations.DeleteModel(
            name='Pricebook',
        ),
        migrations.DeleteModel(
            name='PricebookEntry',
        ),
        migrations.DeleteModel(
            name='SellerProductLocationZone',
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(to='api.useraddress'),
        ),
        migrations.AddField(
            model_name='user',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.seller'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='seller_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sellerproduct'),
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='user_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.useraddress'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.orderdetails'),
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.seller'),
        ),
    ]
