# Generated by Django 4.0.4 on 2022-06-29 16:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrapper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.IntegerField(choices=[(0, 'Individial'), (1, 'Employee')])),
                ('name_first', models.CharField(max_length=120)),
                ('name_middle', models.CharField(max_length=120)),
                ('name_last', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('scrapper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.scrapper')),
                ('address', models.CharField(max_length=1024)),
                ('city', models.CharField(max_length=1024)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('scrapper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.scrapper')),
                ('type', models.IntegerField(choices=[(0, 'Car'), (1, 'SUV/Truck'), (2, 'Box Truck')])),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=1024)),
                ('model', models.CharField(max_length=1024)),
            ],
        ),
    ]
