# Generated by Django 4.1.1 on 2023-02-02 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='active_camp_account_relation_sync_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='active_camp_active_campaign_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='active_camp_active_campaign_sync_status',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='active_camp_last_synced',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='jigsaw',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='jigsaw_contact_id',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sansancard_created_by_scan_to_salesforce',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dhruvsoft_convert_from_opportunity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dhruvsoft_opportunity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dhruvsoft_order_amt_from_opportunity_amt',
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='about_us',
            field=models.TextField(blank=True, null=True, verbose_name='About Us'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_source',
            field=models.CharField(blank=True, choices=[('Advertisement', 'Advertisement'), ('Customer Event', 'Customer Event'), ('Employee Referral', 'Employee Referral'), ('External Referral', 'External Referral'), ('Google AdWords', 'Google AdWords'), ('Other', 'Other'), ('Partner', 'Partner'), ('Purchased List', 'Purchased List'), ('Trade Show', 'Trade Show'), ('Webinar', 'Webinar'), ('Website', 'Website')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='active_camp_active_campaign_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ActiveCampaign Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='active_camp_active_campaign_sync_status',
            field=models.CharField(blank=True, choices=[('Waiting For Next Sync', 'Waiting For Next Sync'), ('Successfully Synced', 'Successfully Synced'), ('Does Not Meet Sync Criteria', 'Does Not Meet Sync Criteria'), ('Waiting For Update', 'Waiting For Update'), ('Account Deleted in ActiveCampaign', 'Account Deleted in ActiveCampaign')], max_length=255, null=True, verbose_name='ActiveCampaign Sync Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='active_camp_last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ActiveCampaign Last Synced'),
        ),
        migrations.AlterField(
            model_name='account',
            name='affordable_housing',
            field=models.BooleanField(default=False, verbose_name='Affordable Housing'),
        ),
        migrations.AlterField(
            model_name='account',
            name='aln_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='ALN ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='account',
            name='average_rent',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Average Rent'),
        ),
        migrations.AlterField(
            model_name='account',
            name='average_unit_size',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Average Unit Size'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_geocode_accuracy',
            field=models.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Billing Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Billing State/Province'),
        ),
        migrations.AlterField(
            model_name='account',
            name='billing_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='book_online_available',
            field=models.BooleanField(default=False, verbose_name='Book Online Available'),
        ),
        migrations.AlterField(
            model_name='account',
            name='builders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_builders_set', to='api.account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Completion Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='composting_classification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Composting Classification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='construction_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Construction Notes'),
        ),
        migrations.AlterField(
            model_name='account',
            name='construction_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Construction Start Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Account Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='dispatch_manager_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Dispatch Manager ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='downstream_insurance_requirements_met',
            field=models.BooleanField(default=False, verbose_name='Downstream Insurance Requirements Met'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fax',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Account Fax'),
        ),
        migrations.AlterField(
            model_name='account',
            name='has_elevators',
            field=models.BooleanField(default=False, verbose_name='Has Elevators'),
        ),
        migrations.AlterField(
            model_name='account',
            name='has_recycling',
            field=models.BooleanField(default=False, verbose_name='Has recycling'),
        ),
        migrations.AlterField(
            model_name='account',
            name='has_valet_trash',
            field=models.BooleanField(default=False, verbose_name='Has Valet Trash'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Apparel', 'Apparel'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemicals', 'Chemicals'), ('Communications', 'Communications'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Electronics', 'Electronics'), ('Energy', 'Energy'), ('Engineering', 'Engineering'), ('Entertainment', 'Entertainment'), ('Environmental', 'Environmental'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Government', 'Government'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Insurance', 'Insurance'), ('Machinery', 'Machinery'), ('Manufacturing', 'Manufacturing'), ('Media', 'Media'), ('Not For Profit', 'Not For Profit'), ('Other', 'Other'), ('Property management', 'Property management'), ('Recreation', 'Recreation'), ('Retail', 'Retail'), ('Shipping', 'Shipping'), ('Technology', 'Technology'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Waste management', 'Waste management'), ('Residential', 'Residential')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='account',
            name='jigsaw',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Data.com Key'),
        ),
        migrations.AlterField(
            model_name='account',
            name='jigsaw_company_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Jigsaw Company ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='account',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Lease Start Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='live_menu_is_active',
            field=models.BooleanField(default=False, verbose_name='Live Menu Is Active'),
        ),
        migrations.AlterField(
            model_name='account',
            name='master_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_masterrecord_set', to='api.account', verbose_name='Master Record ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='max_paint_gallons_accepted',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Max paint gallons accepted'),
        ),
        migrations.AlterField(
            model_name='account',
            name='merchant_type',
            field=models.CharField(blank=True, choices=[('Waste hauler', 'Waste hauler'), ('Landfill', 'Landfill'), ('Recycling facility', 'Recycling facility'), ('Transfer station', 'Transfer station'), ('Scrap yard', 'Scrap yard'), ('Retailer', 'Retailer'), ('Scrapper', 'Scrapper'), ('Equipment manufacturer', 'Equipment manufacturer'), ('Reseller', 'Reseller'), ('Community drop spot', 'Community drop spot'), ('Site services', 'Site services'), ('Equipment rentals', 'Equipment rentals')], max_length=4099, null=True, verbose_name='Merchant Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ncr_status',
            field=models.CharField(blank=True, choices=[('Construction/Lease-Up', 'Construction/Lease-Up'), ('Lease-Up', 'Lease-Up'), ('On hold', 'On hold'), ('Planned', 'Planned'), ('Under Construction', 'Under Construction'), ('Under research', 'Under research')], max_length=255, null=True, verbose_name='NCR Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_buildings',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Number of buildings'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_employees',
            field=models.IntegerField(blank=True, null=True, verbose_name='Employees'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_floors',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Number of floors'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_properties',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Number of Properties'),
        ),
        migrations.AlterField(
            model_name='account',
            name='number_of_units',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Number of units'),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupancy_date',
            field=models.DateField(blank=True, null=True, verbose_name='Occupancy Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='occupancy_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Occupancy Rate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='order_support_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Order Support Email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_parent_set', to='api.account', verbose_name='Parent Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Account Phone'),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='property_ownership',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Property Ownership'),
        ),
        migrations.AlterField(
            model_name='account',
            name='property_type',
            field=models.CharField(blank=True, choices=[('Single Family HOA', 'Single Family HOA'), ('Townhome', 'Townhome'), ('Garden', 'Garden'), ('Mid-Rise', 'Mid-Rise'), ('High-Rise', 'High-Rise'), ('Build-For-Rent', 'Build-For-Rent')], max_length=255, null=True, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='recycling_disposal_classification',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Recycling Disposal Classification'),
        ),
        migrations.AlterField(
            model_name='account',
            name='rent_sq_ft',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Rent/Sq Ft.'),
        ),
        migrations.AlterField(
            model_name='account',
            name='scrap_fleet_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Scrap Fleet ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='scrap_team_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Scrap Team ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='section_8',
            field=models.BooleanField(default=False, verbose_name='Section 8'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_badge',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Pro', 'Pro'), ('Platinum', 'Platinum')], max_length=255, null=True, verbose_name='Seller Badge'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_close_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Seller Close Time'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_lead_time_hrs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Seller Lead Time (hrs)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_location_logo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Seller Location Logo URL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_location_type',
            field=models.CharField(blank=True, choices=[('Services', 'Services'), ('Disposal site', 'Disposal site')], max_length=255, null=True, verbose_name='Seller Location Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_marketplace_display_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Seller Marketplace Display Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_open_days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=4099, null=True, verbose_name='Seller Open Day(s)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_open_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Seller Open Time'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_status',
            field=models.CharField(blank=True, choices=[('Inactive', 'Inactive'), ('Inactive - Onboarding', 'Inactive - Onboarding'), ('Inactive - Pending approval', 'Inactive - Pending approval'), ('Active - under review', 'Active - under review'), ('Active', 'Active')], max_length=255, null=True, verbose_name='Seller Status'),
        ),
        migrations.AlterField(
            model_name='account',
            name='seller_type_display',
            field=models.CharField(blank=True, choices=[('Landfill', 'Landfill'), ('MRF', 'MRF'), ('Industrial', 'Industrial'), ('Scrap yard', 'Scrap yard'), ('Compost facility', 'Compost facility'), ('Processor', 'Processor'), ('Paint recycler', 'Paint recycler'), ('Tires', 'Tires'), ('Other recycler', 'Other recycler'), ('Roll-off', 'Roll-off'), ('Mover', 'Mover'), ('Junk', 'Junk'), ('Delivery', 'Delivery'), ('Broker', 'Broker'), ('Equipment', 'Equipment')], max_length=255, null=True, verbose_name='Seller Type (Display)'),
        ),
        migrations.AlterField(
            model_name='account',
            name='senior_living',
            field=models.BooleanField(default=False, verbose_name='Senior Living'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_geocode_accuracy',
            field=models.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Shipping State/Province'),
        ),
        migrations.AlterField(
            model_name='account',
            name='shipping_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='sic_desc',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='SIC Description'),
        ),
        migrations.AlterField(
            model_name='account',
            name='software_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Software Used'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stripe_connect_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Stripe Connect ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='stripe_customer_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Stripe Customer ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='student_housing',
            field=models.BooleanField(default=False, verbose_name='Student Housing'),
        ),
        migrations.AlterField(
            model_name='account',
            name='tire_recycler_cert_registration_id_co',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tire Recycler Cert Registration ID - CO'),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('Analyst', 'Analyst'), ('Competitor', 'Competitor'), ('Customer', 'Customer'), ('Integrator', 'Integrator'), ('Investor', 'Investor'), ('Partner', 'Partner'), ('Press', 'Press'), ('Prospect', 'Prospect'), ('Seller', 'Seller'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='year_built_renovated',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Year Built/Renovated'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.contact', verbose_name='Contact ID'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='is_direct',
            field=models.BooleanField(default=False, verbose_name='Direct'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='relationship_strength',
            field=models.CharField(blank=True, choices=[('Strong', 'Strong'), ('Neutral', 'Neutral'), ('Weak', 'Weak')], max_length=255, null=True, verbose_name='Relationship Strength'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='roles',
            field=models.CharField(blank=True, choices=[('Business User', 'Business User'), ('Decision Maker', 'Decision Maker'), ('Economic Buyer', 'Economic Buyer'), ('Economic Decision Maker', 'Economic Decision Maker'), ('Evaluator', 'Evaluator'), ('Executive Sponsor', 'Executive Sponsor'), ('Influencer', 'Influencer'), ('Technical Buyer', 'Technical Buyer'), ('Other', 'Other')], max_length=4099, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addon',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Add On Name'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='sort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='add_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon', verbose_name='Add On'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Add On Choice Name'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_account_set', to='api.account', verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='department',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_bounced_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_bounced_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Business Fax'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_email_bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is User'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_curequest_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Stay-in-Touch Request Date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_cuupdate_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Stay-in-Touch Save Date'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_geocode_accuracy',
            field=models.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mailing Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Mailing State/Province'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mailing_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='master_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_masterrecord_set', to='api.contact', verbose_name='Master Record ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=121, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Business Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_property_set', to='api.account'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contact_reportsto_set', to='api.contact', verbose_name='Reports To ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='suffix',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.account'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='location_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.locationzone', verbose_name='Location Zone'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Disposal Fee Name'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wastetype', verbose_name='Waste Type'),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Location Zone Name'),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='ar_url',
            field=models.URLField(blank=True, null=True, verbose_name='AR Url'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='cubic_yards',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Cubic Yards'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='image_del',
            field=models.TextField(blank=True, null=True, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='included_rate_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Included Rate Quantity'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='included_tonnage_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Included Tonnage Quantity'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='max_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Max Rate Quantity'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='max_tonnage_quantity',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Max Tonnage Quantity'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Products Name'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='price_per_additional_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Price Per Additional Ton'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='sort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='add_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon', verbose_name='Add On'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Product Add On Name'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Product Category Name'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='sort',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Product Category Name'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory', verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Product Name'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Main Product Waste Type Name'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wastetype', verbose_name='Waste Type'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='access_details',
            field=models.TextField(blank=True, null=True, verbose_name='Access Details'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opportunity_account_set', to='api.account', verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='active_camp_active_campaign_sync_status',
            field=models.CharField(blank=True, choices=[('Waiting For Next Sync', 'Waiting For Next Sync'), ('Successfully Synced', 'Successfully Synced'), ('Does Not Meet Sync Criteria', 'Does Not Meet Sync Criteria')], max_length=255, null=True, verbose_name='ActiveCampaign Sync Status'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='active_camp_last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ActiveCampaign Last Synced'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='additional_schedule_details',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Schedule Details'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='budget_confirmed',
            field=models.BooleanField(default=False, verbose_name='Budget Confirmed'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.contact', verbose_name='Contact ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='dhruvsoft_is_converted1',
            field=models.BooleanField(default=False, verbose_name='IsConverted'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='dhruvsoft_order_number',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Order Number(Deprecated)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='discovery_completed',
            field=models.BooleanField(default=False, verbose_name='Discovery Completed'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='dispatch_is_active',
            field=models.BooleanField(default=False, verbose_name='Dispatch is active'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End DateTime'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='fiscal',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Fiscal Period'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='fiscal_quarter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='fiscal_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='forecast_category',
            field=models.CharField(choices=[('Omitted', 'Omitted'), ('Pipeline', 'Pipeline'), ('BestCase', 'Best Case'), ('MostLikely', 'Most Likely'), ('Forecast', 'Commit'), ('Closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='forecast_category_name',
            field=models.CharField(blank=True, choices=[('Omitted', 'Omitted'), ('Pipeline', 'Pipeline'), ('Best Case', 'Best Case'), ('Commit', 'Commit'), ('Closed', 'Closed')], max_length=255, null=True, verbose_name='Forecast Category'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='has_open_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='has_opportunity_line_item',
            field=models.BooleanField(default=False, verbose_name='Has Line Item'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='has_overdue_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='is_won',
            field=models.BooleanField(default=False, verbose_name='Won'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='last_activity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Activity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='last_stage_change_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('Advertisement', 'Advertisement'), ('Customer Event', 'Customer Event'), ('Employee Referral', 'Employee Referral'), ('External Referral', 'External Referral'), ('Google AdWords', 'Google AdWords'), ('Other', 'Other'), ('Partner', 'Partner'), ('Purchased List', 'Purchased List'), ('Trade Show', 'Trade Show'), ('Webinar', 'Webinar'), ('Website', 'Website')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='loss_reason',
            field=models.CharField(blank=True, choices=[('Lost to Competitor', 'Lost to Competitor'), ('No Budget / Lost Funding', 'No Budget / Lost Funding'), ('No Decision / Non-Responsive', 'No Decision / Non-Responsive'), ('Price', 'Price'), ('Other', 'Other')], max_length=255, null=True, verbose_name='Loss Reason'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='marketplace_is_active',
            field=models.BooleanField(default=False, verbose_name='Marketplace is active'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='next_step',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='pandadoc_tracking_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tracking Number'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='pricebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pricebook', verbose_name='Price Book ID'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='Probability (%)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='push_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='roi_analysis_completed',
            field=models.BooleanField(default=False, verbose_name='ROI Analysis Completed'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='schedule_date',
            field=models.DateField(blank=True, null=True, verbose_name='Schedule Date'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='scrapper_is_active',
            field=models.BooleanField(default=False, verbose_name='Scrapper is active'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opportunity_serviceprovider_set', to='api.account', verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage_name',
            field=models.CharField(choices=[('Demo Scheduled', 'Demo Scheduled'), ('Demo Performed', 'Demo Performed'), ('Account Configuration', 'Account Configuration'), ('Order Acceptance', 'Order Acceptance'), ('Platform Engagement', 'Platform Engagement'), ('Qualification', 'Qualification'), ('Needs Analysis', 'Needs Analysis'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Verify Hauler', 'Verify Hauler'), ('Closed Won', 'Closed Won'), ('Closed Lost', 'Closed Lost')], max_length=255, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start DateTime'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='time_slot',
            field=models.CharField(blank=True, choices=[('4am-8am', '4am-8am'), ('8am-12pm', '8am-12pm'), ('12pm-4pm', '12pm-4pm'), ('4pm-8pm', '4pm-8pm'), ('8pm-12am', '8pm-12am')], max_length=255, null=True, verbose_name='Time Slot'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='type',
            field=models.CharField(blank=True, choices=[('Existing Business', 'Existing Business'), ('New Business', 'New Business')], max_length=255, null=True, verbose_name='Opportunity Type'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='access_schedule_details',
            field=models.TextField(blank=True, null=True, verbose_name='Access Schedule Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_account_set', to='api.account', verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='activated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_schedule_details',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Schedule Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_geocode_accuracy',
            field=models.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Billing Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Billing State/Province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.contact', verbose_name='Customer Authorized By ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='effective_date',
            field=models.DateField(verbose_name='Order Start Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Order End Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='End DateTime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hauler_payout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Hauler Payout'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_reduction_order',
            field=models.BooleanField(default=False, verbose_name='Reduction Order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order', verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pricebook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pricebook', verbose_name='Price Book ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Scheduled Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scheduled_time_slot',
            field=models.CharField(blank=True, choices=[('4am-8am', '4am-8am'), ('8am-12pm', '8am-12pm'), ('12pm-4pm', '12pm-4pm'), ('4pm-8pm', '4pm-8pm'), ('8pm-12am', '8pm-12am')], max_length=255, null=True, verbose_name='Scheduled Time Slot'),
        ),
        migrations.AlterField(
            model_name='order',
            name='scrap_task_id',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True, verbose_name='Scrap Task ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_serviceprovider_set', to='api.account', verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_geocode_accuracy',
            field=models.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Shipping Zip/Postal Code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Shipping State/Province'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_street',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Start DateTime'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Pending_Acceptance', 'Pending Acceptance'), ('Declined', 'Declined'), ('Accepted', 'Accepted'), ('On the way', 'On the way'), ('Arrived', 'Arrived'), ('Price Changed', 'Price Changed'), ('Price Approved', 'Price Approved'), ('Complete', 'Complete'), ('Invoiced', 'Invoiced'), ('Paid_To_Hauler', 'Paid To Hauler'), ('Paid_By_Customer', 'Paid By Customer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_code',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Activated', 'Activated'), ('Canceled', 'Cancelled'), ('Expired', 'Expired')], max_length=40, verbose_name='Status Category'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Order Amount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Order Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='county',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='location_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.locationzone', verbose_name='Location Zone'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Postal Code Name'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='state_abbreviation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='State Abbreviation'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='is_standard',
            field=models.BooleanField(default=False, verbose_name='Is Standard Price Book'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Price Book Name'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='pricebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.pricebook', verbose_name='Price Book ID'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product', verbose_name='Product ID'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='List Price'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='use_standard_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(blank=True, choices=[('Denver', 'Denver')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_url',
            field=models.URLField(blank=True, null=True, verbose_name='Display URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='External ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='family',
            field=models.CharField(blank=True, choices=[('Junk', 'Junk'), ('Business Dumpster', 'Business Dumpster'), ('Large Dumpster', 'Large Dumpster'), ('Apartment Services', 'Apartment Services'), ('Dispatch - SaaS', 'Dispatch - SaaS'), ('Site_Services', 'Site Services')], max_length=255, null=True, verbose_name='Product Family'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct', verbose_name='Main Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_quantity_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='number_of_revenue_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('Service', 'Service'), ('Drop off', 'Drop off')], max_length=255, null=True, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_installment_period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_schedule_type',
            field=models.CharField(blank=True, choices=[('Divide', 'Divide Amount into multiple installments'), ('Repeat', 'Repeat Amount for each installment')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_unit_of_measure',
            field=models.CharField(blank=True, choices=[('Each', 'Each')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='revenue_installment_period',
            field=models.CharField(blank=True, choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly'), ('Yearly', 'Yearly')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='revenue_schedule_type',
            field=models.CharField(blank=True, choices=[('Divide', 'Divide Amount into multiple installments'), ('Repeat', 'Repeat Amount for each installment')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('Incomplete', 'Incomplete'), ('Ready for Review', 'Ready for Review'), ('Under Review', 'Under Review'), ('Rejected', 'Rejected'), ('Approved', 'Approved')], default='Incomplete', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_keeping_unit',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Product SKU'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='add_on_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.addonchoice', verbose_name='Add On Choice'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Product Add On Choice Name'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Seller Product Name'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.account', verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='location_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.locationzone', verbose_name='Location Zone'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Seller Product Location Zone Name'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='pickup_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Pickup Fee'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='seller_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.sellerproduct', verbose_name='Seller Product'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Waste Type Name'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
