# Generated by Django 4.1.1 on 2023-02-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='accountcontactrelation',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='addon',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='disposalfee',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='locationzone',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='postalcode',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='pricebook',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='pricebookentry',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='sellerproductlocationzone',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_column='CreatedDate'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, db_column='LastModifiedDate'),
        ),
    ]
