# Generated by Django 4.1 on 2023-02-22 19:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_orderdetails_orderdetailslineitem_seller_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("subscription_number", models.CharField(max_length=255)),
                ("interval_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="hauler_payout",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_details",
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.order",
            ),
        ),
        migrations.AddField(
            model_name="sellerproduct",
            name="total_inventory",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sellerproduct",
            name="seller",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seller_products",
                to="api.seller",
            ),
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.subscription",
            ),
        ),
    ]
