# Generated by Django 4.1.1 on 2023-03-27 19:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_device_token_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisposalLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='main_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.wastetype'),
        ),
        migrations.CreateModel(
            name='DisposalLocationWasteType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disposal_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disposallocation')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
