# Generated by Django 4.2.11 on 2024-05-09 19:42

import api.models.user.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.user.user.User.get_file_path),
        ),
    ]
