# Generated by Django 4.0.4 on 2022-06-29 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scrapper_delete_todo_address_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('scrapper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.scrapper')),
                ('name_first', models.CharField(max_length=120)),
                ('name_middle', models.CharField(max_length=120)),
                ('name_last', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='name_first',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='name_last',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='name_middle',
        ),
        migrations.RemoveField(
            model_name='scrapper',
            name='phone',
        ),
        migrations.AlterField(
            model_name='scrapper',
            name='type',
            field=models.IntegerField(choices=[(0, 'Individual'), (1, 'Employee')]),
        ),
    ]
