# Generated by Django 4.1.1 on 2023-03-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disposallocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
