# Generated by Django 4.1 on 2024-05-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_addon_created_by_addon_updated_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraddress",
            name="child_account_id",
        ),
        migrations.AddField(
            model_name="useraddress",
            name="allow_saturday_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="allow_sunday_delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="street2",
            field=models.TextField(blank=True, null=True),
        ),
    ]
