# Generated by Django 4.1 on 2023-02-24 18:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_sellerproduct_product_alter_user_addresses_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sellerproduct",
            name="rate",
        ),
        migrations.RemoveField(
            model_name="sellerproduct",
            name="total_inventory",
        ),
        migrations.CreateModel(
            name="SellerProductSellerLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=18, null=True
                    ),
                ),
                (
                    "total_inventory",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=18, null=True
                    ),
                ),
                (
                    "seller_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="seller_location_product",
                        to="api.sellerlocation",
                    ),
                ),
                (
                    "seller_product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="seller_location_product",
                        to="api.sellerproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
