# Generated by Django 4.1 on 2023-03-01 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_sellerproduct_rate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="stripe_invoice_id",
        ),
        migrations.RemoveField(
            model_name="orderdetails",
            name="seller_product",
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="seller_product_seller_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.sellerproductsellerlocation",
            ),
        ),
        migrations.AddField(
            model_name="orderdetails",
            name="stripe_invoice_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="sellerproductsellerlocation",
            name="seller_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seller_location_seller_product",
                to="api.sellerlocation",
            ),
        ),
        migrations.AlterField(
            model_name="sellerproductsellerlocation",
            name="seller_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="seller_location_seller_product",
                to="api.sellerproduct",
            ),
        ),
        migrations.CreateModel(
            name="UserSellerReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_seller_review",
                        to="api.seller",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="user_seller_review",
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
