# Generated by Django 4.1 on 2024-05-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_useraddress_child_account_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerinvoicepayable",
            name="due_date",
            field=models.DateField(null=True),
        ),
    ]
