# Generated by Django 4.1.1 on 2023-03-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='disposal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.disposallocation'),
        ),
        migrations.AddField(
            model_name='order',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.wastetype'),
        ),
    ]
