# Generated by Django 4.1 on 2023-03-04 20:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_order_stripe_invoice_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DevEnvironTest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
