# Generated by Django 4.1.1 on 2023-03-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_disposal_location_order_waste_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='schedule_date',
            new_name='end_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
