# Generated by Django 4.0.4 on 2022-07-04 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_address_scrapper_alter_contact_scrapper_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='scrapper',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='scrapper',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Scrapper',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
