# Generated by Django 4.1 on 2023-03-01 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_order_stripe_invoice_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
