# Generated by Django 4.1 on 2023-04-09 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_schedule_date_order_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="marketplace_display_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Broker", "Broker"),
                    ("Compost facility", "Compost facility"),
                    ("Delivery", "Delivery"),
                    ("Equipment", "Equipment"),
                    ("Fencing", "Fencing"),
                    ("Industrial", "Industrial"),
                    ("Junk", "Junk"),
                    ("Landfill", "Landfill"),
                    ("Mover", "Mover"),
                    ("MRF", "MRF"),
                    ("Other recycler", "Other recycler"),
                    ("Paint recycler", "Paint recycler"),
                    ("Portable Storage", "Portable Storage"),
                    ("Portable Toilet", "Portable Toilet"),
                    ("Processor", "Processor"),
                    ("Roll-off", "Roll-off"),
                    ("Scrap yard", "Scrap yard"),
                    ("Tires", "Tires"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
