# Generated by Django 4.2.13 on 2024-06-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_order_status_ordergroupsellerdecline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='lob_check_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
