# Generated by Django 4.1.1 on 2023-03-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_devenvirontest'),
        ('api', '0007_order_order_number'),
    ]

    operations = [
    ]
