# Generated by Django 4.1 on 2024-06-11 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_remove_conversation_users"),
        ("api", "0008_ordergroup_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.conversation"
            ),
        ),
    ]
