# Generated by Django 4.1.1 on 2023-04-09 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_seller_marketplace_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproductaddon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='useruseraddress',
            name='name',
        ),
        migrations.AlterField(
            model_name='addon',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addon',
            name='sort',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='main_product_category',
            field=models.ForeignKey(default='a975baa7-3db5-4540-90d6-0cd550df9d42', on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='sort',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='add_on',
            field=models.ForeignKey(default='b7c80a58-96e7-4c8f-86f2-17c6615879c3', on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='sort',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='main_product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='main_product',
            field=models.ForeignKey(default='cb2f6230-e18e-4f52-aacf-29d17dad1dc0', on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wastetype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(default='cb2f6230-e18e-4f52-aacf-29d17dad1dc0', on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.product'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='lead_time_hrs',
            field=models.DecimalField(decimal_places=0, default=24.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='city',
            field=models.CharField(default='Change Me', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='country',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='postal_code',
            field=models.CharField(default='Change Me', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.seller'),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='state',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='city',
            field=models.CharField(default='Change Me', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(default='Change Me', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useruseraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.user'),
        ),
        migrations.AlterField(
            model_name='useruseraddress',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.useraddress'),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='name',
            field=models.CharField(default='Change Me', max_length=80),
            preserve_default=False,
        ),
    ]
