# Generated by Django 4.1 on 2023-03-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_merge_0007_devenvirontest_0007_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="addresses",
        ),
    ]
