# Generated by Django 4.1 on 2024-06-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_message_conversation_and_more"),
        ("api", "0009_alter_ordergroup_conversation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroup",
            name="conversation",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="ordergroup",
            name="seller_product_seller_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_groups",
                to="api.sellerproductsellerlocation",
            ),
        ),
    ]
