# Generated by Django 4.1.1 on 2023-04-12 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_mainproductaddon_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addon',
            name='main_product',
            field=models.ForeignKey(default='f8be2646-081f-4e3e-8f01-6c9122834e32', on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='main_product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='add_on_choice',
            field=models.ForeignKey(default='7f888bb9-f089-492b-a27d-4753c20b8b0f', on_delete=django.db.models.deletion.DO_NOTHING, to='api.addonchoice'),
            preserve_default=False,
        ),
    ]
