# Generated by Django 4.2.13 on 2024-06-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_ordergroup_conversation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitemtype',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
