# Generated by Django 3.2.5 on 2023-04-16 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_addon_main_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='main_product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addon'),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='main_product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='add_on_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addonchoice'),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.seller'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='api.product'),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='api.seller'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_product', to='api.sellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_product', to='api.sellerproduct'),
        ),
        migrations.AlterField(
            model_name='useruseraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AlterField(
            model_name='useruseraddress',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useraddress'),
        ),
    ]
