# Generated by Django 4.1 on 2023-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_auto_20230416_2355"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproduct",
            name="main_product_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mainproductcategory",
            name="main_product_category_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
