# Generated by Django 4.1.1 on 2023-04-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_mainproduct_main_product_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproductcategoryinfo',
            name='sort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainproductinfo',
            name='sort',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
