# Generated by Django 4.2.13 on 2024-06-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_usersellerlocation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='redirect_url',
            field=models.CharField(blank=True, help_text='URL to redirect to after Auth0 login (defaults to webapp settings.BASE_URL).', max_length=255, null=True),
        ),
    ]
