# Generated by Django 4.1 on 2024-06-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_user_redirect_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="payout",
            name="lob_check_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
