# Generated by Django 4.2.13 on 2024-06-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_payout_lob_check_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='check_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
