# Generated by Django 4.2.13 on 2024-06-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_sellerproductsellerlocationrentalmultistep'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='intercom_id',
            field=models.CharField(blank=True, help_text='The Intercom ID of the Conversation object.', max_length=128, null=True),
        ),
    ]
