# Generated by Django 4.1 on 2024-07-02 13:02

import api.models.main_product.main_product_category
import common.utils.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_ordergroup_intercom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproductcategory",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=common.utils.get_file_path.get_file_path,
                validators=[
                    api.models.main_product.main_product_category.MainProductCategory.validate_file_extension
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("APPROVAL", "Approval"),
                    ("PENDING", "Pending"),
                    ("SCHEDULED", "Scheduled"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETE", "Complete"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
