# Generated by Django 4.2.13 on 2024-07-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_ordergroup_intercom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='intercom_id',
        ),
        migrations.AddField(
            model_name='order',
            name='custmer_intercom_id',
            field=models.CharField(blank=True, help_text='Conversation between Seller and Customer.', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='intercom_id',
            field=models.CharField(blank=True, help_text='Conversation between Seller and Admin.', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20),
        ),
    ]
