# Generated by Django 4.2.13 on 2024-07-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_mainproductcategory_icon_alter_order_status'),
        ('api', '0018_remove_ordergroup_intercom_id_and_more'),
    ]

    operations = [
    ]
