# Generated by Django 4.1.1 on 2023-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_useraddresstype_useraddress_user_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesforce_order_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
