# Generated by Django 4.1 on 2024-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_merge_20240705_1933"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproduct",
            name="has_rental_multi_step",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="mainproduct",
            name="has_rental_one_step",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sellerproductsellerlocationrental",
            name="price_per_day_additional",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="sellerproductsellerlocationrental",
            name="price_per_day_included",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
