# Generated by Django 4.1.1 on 2023-05-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_salesforce_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN-PROGRESS', 'In-Progress'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20),
        ),
    ]
