# Generated by Django 4.1.1 on 2023-05-14 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='month',
            new_name='status',
        ),
    ]
