# Generated by Django 4.1.1 on 2023-06-01 16:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_rename_month_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDisposalTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('ticket_id', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=18)),
                ('disposal_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.disposallocation')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.order')),
                ('waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.wastetype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
