# Generated by Django 4.1 on 2024-07-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_mainproduct_has_service_times_per_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproducttag",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
