# Generated by Django 4.1.1 on 2023-06-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_orderdisposalticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='pay_later',
            field=models.BooleanField(default=False),
        ),
    ]
