# Generated by Django 4.2.13 on 2024-07-26 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_mainproducttag_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinvoicepayable',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='addon',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='add_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='api.addon'),
        ),
    ]
