# Generated by Django 4.1 on 2023-06-07 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_usergroup_pay_later"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="additional_schedule_details",
            new_name="billing_comments_internal_use",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="description",
            new_name="payout_processing_error_comment",
        ),
        migrations.AddField(
            model_name="order",
            name="included_weight_tons",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not yet invoiced", "Not yet invoiced"),
                    ("In draft", "In draft"),
                    ("Sent to customer", "Sent to customer"),
                    ("Paid", "Paid"),
                ],
                default=0,
                max_length=35,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Automatic Renewal", "Automatic Renewal"),
                    ("Swap", "Swap"),
                    ("Empty and Return", "Empty and Return"),
                    ("Trip Charge/Dry Run", "Trip Charge/Dry Run"),
                    ("Removal", "Removal"),
                    ("On Demand", "On Demand"),
                    ("Other", "Other"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="placement_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="schedule_details",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="schedule_window",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Morning (7am-11am)", "Morning (7am-11am)"),
                    ("Afternoon (12pm-4pm)", "Afternoon (12pm-4pm)"),
                    ("Evening (5pm-8pm)", "Evening (5pm-8pm)"),
                ],
                max_length=35,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_payout_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Not yet paid", "Not yet paid"),
                    ("Process Payment", "Process Payment"),
                    ("Payout Processing Error", "Payout Processing Error"),
                    ("Payout Completed", "Payout Completed"),
                ],
                default=0,
                max_length=35,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="suppplier_payout_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Stripe Connect", "Stripe Connect"),
                    ("By Invoice", "By Invoice"),
                    ("Other", "Other"),
                ],
                max_length=35,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="removal_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="length_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "On demand without subscription",
                        "On demand without subscription",
                    ),
                    ("On demand with subscription", "On demand with subscription"),
                    (
                        "Auto scheduled with subscription",
                        "Auto scheduled with subscription",
                    ),
                ],
                max_length=35,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="intercom_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mailchip_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="autopay",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="project_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="autopay",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SCHEDULED", "Scheduled"),
                    ("IN-PROGRESS", "In-Progress"),
                    ("Awaiting Request", "Awaiting Request"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETE", "Complete"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="open_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
