# Generated by Django 4.1 on 2024-07-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0025_sellerinvoicepayable_account_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mainproduct",
            name="cubic_yards",
        ),
        migrations.RemoveField(
            model_name="mainproduct",
            name="included_rate_quantity",
        ),
        migrations.RemoveField(
            model_name="mainproduct",
            name="max_rate",
        ),
        migrations.RemoveField(
            model_name="mainproduct",
            name="price_per_additional_ton",
        ),
        migrations.AddField(
            model_name="mainproduct",
            name="default_take_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default mark up for this product (ex: 35%)",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="mainproduct",
            name="minimum_take_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum take rate for this product (ex: 10%)",
                max_digits=18,
                null=True,
            ),
        ),
    ]
