# Generated by Django 4.1.1 on 2023-06-07 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_additional_schedule_details_order_billing_comments_internal_use_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='seller_product_seller_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_address',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='seller_product_seller_location',
            field=models.ForeignKey(default='9596a5e5-7c73-45fd-9b22-019ba3e9ddb2', on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.subscription'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='user',
            field=models.ForeignKey(default='9596a5e5-7c73-45fd-9b22-019ba3e9ddb2', on_delete=django.db.models.deletion.PROTECT, to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='user_address',
            field=models.ForeignKey(default='9596a5e5-7c73-45fd-9b22-019ba3e9ddb2', on_delete=django.db.models.deletion.PROTECT, to='api.useraddress'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(default='9596a5e5-7c73-45fd-9b22-019ba3e9ddb2', on_delete=django.db.models.deletion.PROTECT, to='api.ordergroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='salesforce_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
