# Generated by Django 4.1 on 2024-07-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0026_remove_mainproduct_cubic_yards_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainproduct",
            name="default_take_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Default mark up for this product (ex: 35 == 35%)",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="mainproduct",
            name="minimum_take_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                help_text="Minimum take rate for this product (ex: 10 == 10%)",
                max_digits=18,
            ),
        ),
    ]
