# Generated by Django 4.1 on 2023-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_user_is_archived_useraddress_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seller",
            name="composting_classification",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="max_paint_gallons_accepted",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="recycling_disposal_classification",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="tire_recycler_cert_registration_id_co",
        ),
        migrations.AddField(
            model_name="seller",
            name="about_us",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seller",
            name="salesforce_seller_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sellerproductsellerlocation",
            name="rate_per_day",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="sellerproductsellerlocation",
            name="rate_per_mile",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="sellerproductsellerlocation",
            name="rate_per_ton",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="salesforce_contact_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="salesforce_seller_location_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="useraddress",
            name="child_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="usergroup",
            name="parent_account_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="seller",
            name="open_days",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MONDAY", "MONDAY"),
                    ("TUESDAY", "TUESDAY"),
                    ("WEDNESDAY", "WEDNESDAY"),
                    ("THURSDAY", "THURSDAY"),
                    ("FRIDAY", "FRIDAY"),
                    ("SATURDAY", "SATURDAY"),
                    ("SUNDAY", "SUNDAY"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="seller",
            name="stripe_connect_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
