# Generated by Django 4.2.13 on 2024-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_mainproduct_default_take_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddresstype',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
