# Generated by Django 4.1.1 on 2023-06-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_seller_composting_classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submitted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
