# Generated by Django 4.2.13 on 2024-07-31 16:36

import common.utils.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_useraddresstype_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='credit_report',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='owned_and_rented_equiptment_coi',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path),
        ),
    ]
