# Generated by Django 4.1.1 on 2023-06-15 21:14

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_order_submitted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='waste_type',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='waste_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.wastetype'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='open_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=255, null=True),
        ),
    ]
