# Generated by Django 4.2.13 on 2024-08-06 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_usergroup_credit_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroupServiceTimesPerWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('one_time_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('two_times_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('three_times_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('four_times_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('five_times_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_times_per_week', to='api.ordergroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGroupRentalOneStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_one_step', to='api.ordergroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGroupRentalMultiStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('hour', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('day', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('week', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('two_weeks', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('month', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental_multi_step', to='api.ordergroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
