# Generated by Django 4.1.1 on 2023-07-03 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_orderlineitemtype_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProductSellerProductSellerLocationServiceRecurringFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mainproduct')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tonnage_included', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price_per_mile', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('flat_rate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationServiceRecurringFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sellerproductsellerlocation',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='sellerproductsellerlocation',
            name='rate_per_day',
        ),
        migrations.RemoveField(
            model_name='sellerproductsellerlocation',
            name='rate_per_mile',
        ),
        migrations.RemoveField(
            model_name='sellerproductsellerlocation',
            name='rate_per_ton',
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='fuel_environmental_markup',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='removal_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='service_radius',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationServiceRecurring',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('main_product_seller_product_seller_location_service_recurring_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mainproductsellerproductsellerlocationservicerecurringfrequency')),
                ('seller_product_seller_location_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocationservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocationservice',
            name='seller_product_seller_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sellerproductsellerlocation'),
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('included_days', models.IntegerField()),
                ('price_per_day_included', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('price_per_day_additional', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('seller_product_seller_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sellerproductsellerlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellerProductSellerLocationMaterialPricingWasteType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price_per_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('main_product_waste_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mainproductwastetype')),
                ('seller_product_seller_location_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocationmaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocationmaterial',
            name='seller_product_seller_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sellerproductsellerlocation'),
        ),
        migrations.AddField(
            model_name='mainproductsellerproductsellerlocationservicerecurringfrequency',
            name='seller_product_seller_location_service_recurring_frequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocationservicerecurringfrequency'),
        ),
    ]
