# Generated by Django 4.2.13 on 2024-08-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_sellerinvoicepayablelineitem_seller_invoice_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='times_per_week',
            field=models.SmallIntegerField(blank=True, help_text='Service times times per week for MainProducts that have has_service_times_per_week.', null=True),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='fuel_environmental_markup',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage (ex: 35 means 35%)', max_digits=18, null=True),
        ),
    ]
