# Generated by Django 4.1.1 on 2023-07-03 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_mainproductsellerproductsellerlocationservicerecurringfrequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addon',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addonchoice',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disposallocation',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='disposallocationwastetype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductaddon',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategory',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductcategoryinfo',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductinfo',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductsellerproductsellerlocationservicerecurringfrequency',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mainproductwastetype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdisposalticket',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderlineitemtype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seller',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterial',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterialpricingwastetype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationrental',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationservice',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationservicerecurring',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationservicerecurringfrequency',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useraddresstype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usergroupuser',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersellerreview',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useruseraddress',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
