# Generated by Django 4.1 on 2024-08-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0033_ordergroup_times_per_week_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroupservice",
            name="flat_rate_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="ordergroupservice",
            name="price_per_mile",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ordergroupmaterial",
            name="price_per_ton",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Deprecated. Use OrderGroupMaterialWasteType(s) instead of this field.",
                max_digits=18,
            ),
        ),
        migrations.AlterField(
            model_name="ordergroupmaterial",
            name="tonnage_included",
            field=models.IntegerField(
                default=0,
                help_text="Deprecated. Use OrderGroupMaterialWasteType(s) instead of this field.",
            ),
        ),
        migrations.AlterField(
            model_name="ordergrouprental",
            name="price_per_day_additional",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ordergrouprental",
            name="price_per_day_included",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ordergroupservice",
            name="miles",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deprecated. Use price_per_mile and flat_rate_price instead.",
                max_digits=18,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ordergroupservice",
            name="rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Deprecated. Use price_per_mile and flat_rate_price instead.",
                max_digits=18,
                null=True,
            ),
        ),
    ]
