# Generated by Django 4.1 on 2024-08-14 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0035_ordergroupmaterialwastetype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordergroupmaterialwastetype",
            name="order_group_material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="waste_types",
                to="api.ordergroupmaterial",
            ),
        ),
    ]
