# Generated by Django 4.1.1 on 2023-07-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_addon_id_alter_addonchoice_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerProductSellerLocationMaterialPricingWasteType',
            new_name='SellerProductSellerLocationMaterialWasteType',
        ),
    ]
