# Generated by Django 4.2.13 on 2024-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_ordergroupmaterialwastetype_order_group_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='schedule_window',
            field=models.CharField(blank=True, choices=[('Anytime (7am-4pm)', 'Anytime (7am-4pm)'), ('Morning (7am-11am)', 'Morning (7am-11am)'), ('Afternoon (12pm-4pm)', 'Afternoon (12pm-4pm)'), ('Evening (5pm-8pm)', 'Evening (5pm-8pm)')], max_length=35, null=True),
        ),
    ]
