# Generated by Django 4.1.1 on 2023-07-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_rename_sellerproductsellerlocationmaterialpricingwastetype_sellerproductsellerlocationmaterialwastet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductsellerlocationservicerecurringfrequency',
            name='name',
            field=models.CharField(default='TEST', max_length=255),
            preserve_default=False,
        ),
    ]
