# Generated by Django 4.1.1 on 2023-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_sellerproductsellerlocationservicerecurringfrequency_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
