# Generated by Django 4.2.13 on 2024-08-27 20:05

import api.models.order.order_group_attachment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_ordergroupattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroupattachment',
            name='file',
            field=models.FileField(upload_to=api.models.order.order_group_attachment.OrderGroupAttachment.get_file_path),
        ),
    ]
