# Generated by Django 4.1.1 on 2023-07-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_sellerproductsellerlocation_max_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainProductSellerProductSellerLocationServiceRecurringFrequency',
            new_name='MainProductServiceRecurringFrequency',
        ),
        migrations.RenameModel(
            old_name='SellerProductSellerLocationServiceRecurringFrequency',
            new_name='ServiceRecurringFrequency',
        ),
        migrations.RenameField(
            model_name='mainproductservicerecurringfrequency',
            old_name='seller_product_seller_location_service_recurring_frequency',
            new_name='service_recurring_frequency',
        ),
    ]
