# Generated by Django 4.1.1 on 2023-07-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_rename_mainproductsellerproductsellerlocationservicerecurringfrequency_mainproductservicerecurringfr'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='has_material',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='has_rental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='has_service',
            field=models.BooleanField(default=False),
        ),
    ]
