# Generated by Django 4.2.13 on 2024-08-28 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('api', '0039_alter_ordergroupattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.cartorder'),
        ),
    ]
