# Generated by Django 4.1.1 on 2023-07-06 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_mainproduct_has_material_mainproduct_has_rental_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterial',
            name='seller_product_seller_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.sellerproductsellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterialwastetype',
            name='price_per_ton',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationrental',
            name='included_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationrental',
            name='price_per_day_additional',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationrental',
            name='price_per_day_included',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationrental',
            name='seller_product_seller_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='api.sellerproductsellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationservice',
            name='seller_product_seller_location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.sellerproductsellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationservicerecurring',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
