# Generated by Django 4.2.13 on 2024-08-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_order_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ADMIN_APPROVAL_PENDING', 'Admin Approval Pending'), ('ADMIN_APPROVAL_DECLINED', 'Admin Approval Declined'), ('PENDING', 'Supplier confirmation pending'), ('SCHEDULED', 'Scheduled'), ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete'), ('CREDIT_APPLICATION_APPROVAL_PENDING', 'Credit Application Approval Pending'), ('CREDIT_APPLICATION_DECLINED', 'Credit Application Declined'), ('NO_PAYMENT_METHOD', 'No Payment Method')], default='PENDING', max_length=50),
        ),
    ]
