# Generated by Django 4.2.13 on 2024-08-30 17:22

import common.utils.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroupcreditapplication',
            name='accepts_credit_authorization',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usergroupcreditapplication',
            name='credit_report',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path),
        ),
        migrations.AddField(
            model_name='usergroupcreditapplication',
            name='estimated_monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='usergroupcreditapplication',
            name='estimated_monthly_spend',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='usergrouplegal',
            name='accepted_net_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergrouplegal',
            name='tax_id',
            field=models.CharField(blank=True, help_text='EIN/TIN or SSN', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usergrouplegal',
            name='years_in_business',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
