# Generated by Django 4.1.1 on 2023-07-06 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_sellerproductsellerlocationmaterial_seller_product_seller_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
