# Generated by Django 4.1.1 on 2023-07-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sellerproductsellerlocation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterial',
            name='tonnage_included',
            field=models.IntegerField(default=0),
        ),
    ]
