# Generated by Django 4.2.13 on 2024-08-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_usergroupcreditapplication_accepts_credit_authorization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='credit_report',
        ),
    ]
