# Generated by Django 4.1.1 on 2023-07-06 16:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_sellerproductsellerlocationmaterial_tonnage_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProductSellerLocationServiceRecurringFrequency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('main_product_service_recurring_frequency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mainproductservicerecurringfrequency')),
                ('seller_product_seller_location_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerproductsellerlocationservice')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SellerProductSellerLocationServiceRecurring',
        ),
    ]
