# Generated by Django 4.1 on 2024-09-03 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0043_remove_usergroup_credit_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroup",
            name="shift_count",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "One Shift"), (2, "Two Shifts"), (3, "Three Shifts")],
                help_text="For multi-step rentals, this field contains the number of daily working shifts the customer plans to use the equiptment for.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="SellerProductSellerLocationRentalMultiStepShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "two_shift",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The multiplier for the two shift rental period. For example, if the two shift rental period is 1.5 times the hourly rate, this field should be 1.5.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "three_shift",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The multiplier for the three shift rental period. For example, if the three shift rental period is 2 times the hourly rate, this field should be 2.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_product_seller_location_multi_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_multi_step_shift",
                        to="api.sellerproductsellerlocationrentalmultistep",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderGroupRentalMultiStepShift",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "two_shift",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The multiplier for the two shift rental period. For example, if the two shift rental period is 1.5 times the hourly rate, this field should be 1.5.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "three_shift",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The multiplier for the three shift rental period. For example, if the three shift rental period is 2 times the hourly rate, this field should be 2.",
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order_group_rental_multi_step",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_multi_step_shift",
                        to="api.ordergrouprentalmultistep",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
