# Generated by Django 4.2.3 on 2023-07-10 19:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_sellerproductsellerlocationservicerecurringfrequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='end_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='start_date',
            field=models.DateField(default='2023-01-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='sellerproductsellerlocationmaterialwastetype',
            unique_together={('seller_product_seller_location_material', 'main_product_waste_type')},
        ),
        migrations.AlterUniqueTogether(
            name='sellerproductsellerlocationservicerecurringfrequency',
            unique_together={('seller_product_seller_location_service', 'main_product_service_recurring_frequency')},
        ),
    ]
