# Generated by Django 4.2.13 on 2024-09-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_ordergroup_shift_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the Transaction.', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the Order.', max_length=8, null=True, unique=True),
        ),
    ]
