# Generated by Django 4.2.3 on 2023-07-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_timeslot_ordergroup_end_date_ordergroup_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='time_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.timeslot'),
        ),
    ]
