# Generated by Django 4.2.13 on 2024-09-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_order_code_ordergroup_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addon',
            options={'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterModelOptions(
            name='addonchoice',
            options={'verbose_name': 'Variant Choice', 'verbose_name_plural': 'Variants Choices'},
        ),
        migrations.AlterModelOptions(
            name='mainproduct',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='mainproductcategory',
            options={'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
        migrations.AlterModelOptions(
            name='mainproductcategoryinfo',
            options={'verbose_name': 'Product Category Info', 'verbose_name_plural': 'Product Category Infos'},
        ),
        migrations.AlterModelOptions(
            name='mainproductinfo',
            options={'verbose_name': 'Product Info', 'verbose_name_plural': 'Product Infos'},
        ),
        migrations.AlterModelOptions(
            name='mainproducttag',
            options={'verbose_name': 'Product Tag', 'verbose_name_plural': 'Product Tags'},
        ),
        migrations.AlterModelOptions(
            name='mainproductwastetype',
            options={'verbose_name': 'Product Waste Type', 'verbose_name_plural': 'Product Waste Types'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterModelOptions(
            name='orderdisposalticket',
            options={'verbose_name': 'Transaction Disposal Ticket', 'verbose_name_plural': 'Transaction Disposal Tickets'},
        ),
        migrations.AlterModelOptions(
            name='ordergroup',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupattachment',
            options={'verbose_name': 'Booking Attachment', 'verbose_name_plural': 'Booking Attachments'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupmaterial',
            options={'verbose_name': 'Booking Rental Material', 'verbose_name_plural': 'Booking Rentals Material'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupmaterialwastetype',
            options={'verbose_name': 'Booking Material Waste Type', 'verbose_name_plural': 'Booking Materials Waste Type'},
        ),
        migrations.AlterModelOptions(
            name='ordergrouprental',
            options={'verbose_name': 'Booking Rental Two Step', 'verbose_name_plural': 'Booking Rentals Two Step'},
        ),
        migrations.AlterModelOptions(
            name='ordergrouprentalmultistep',
            options={'verbose_name': 'Booking Rental Multi Step', 'verbose_name_plural': 'Booking Rentals Multi Step'},
        ),
        migrations.AlterModelOptions(
            name='ordergrouprentalmultistepshift',
            options={'verbose_name': 'Booking Rental Multi Step Shift', 'verbose_name_plural': 'Booking Rentals Multi Step Shift'},
        ),
        migrations.AlterModelOptions(
            name='ordergrouprentalonestep',
            options={'verbose_name': 'Booking Rental One Step', 'verbose_name_plural': 'Booking Rentals One Step'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupsellerdecline',
            options={'verbose_name': 'Booking Seller Decline', 'verbose_name_plural': 'Booking Seller Declines'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupservice',
            options={'verbose_name': 'Booking Service (Legacy)', 'verbose_name_plural': 'Booking Services (Legacy)'},
        ),
        migrations.AlterModelOptions(
            name='ordergroupservicetimesperweek',
            options={'verbose_name': 'Booking Service Times Per Week', 'verbose_name_plural': 'Booking Services Times Per Week'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'verbose_name': 'Transaction Line Item', 'verbose_name_plural': 'Transaction Line Items'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitemtype',
            options={'verbose_name': 'Transaction Line Item Type', 'verbose_name_plural': 'Transaction Line Item Types'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product Variant', 'verbose_name_plural': 'Product Variants'},
        ),
        migrations.AlterModelOptions(
            name='productaddonchoice',
            options={'verbose_name': 'Product Variant Choice', 'verbose_name_plural': 'Product Variants Choices'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='usergroupuser',
            options={'verbose_name': 'Account User', 'verbose_name_plural': 'Account Users'},
        ),
    ]
