# Generated by Django 4.2.3 on 2023-07-25 18:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_ordergroup_time_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('number', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='access_details',
        ),
        migrations.RemoveField(
            model_name='order',
            name='placement_details',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='subscription_type',
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='access_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='placement_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.servicerecurringfrequency'),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='preferred_service_days',
            field=models.ManyToManyField(blank=True, to='api.dayofweek'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='service_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.dayofweek'),
        ),
    ]
