# Generated by Django 4.2.13 on 2024-09-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_addon_options_alter_addonchoice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='orderdisposalticket',
            options={'verbose_name': 'Event Disposal Ticket', 'verbose_name_plural': 'Event Disposal Tickets'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'verbose_name': 'Event Line Item', 'verbose_name_plural': 'Event Line Items'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitemtype',
            options={'verbose_name': 'Event Line Item Type', 'verbose_name_plural': 'Event Line Item Types'},
        ),
    ]
