# Generated by Django 4.2.3 on 2023-07-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_dayofweek_remove_order_access_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordergroup',
            name='subscription',
        ),
        migrations.AddField(
            model_name='subscription',
            name='order_group',
            field=models.ForeignKey(default='6771f831-bd36-4fee-8710-cba0cd43e6d8', on_delete=django.db.models.deletion.PROTECT, to='api.ordergroup'),
            preserve_default=False,
        ),
    ]
