# Generated by Django 4.2.13 on 2024-09-09 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_order_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart_order',
        ),
    ]
