# Generated by Django 4.2.13 on 2024-09-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkoutorder_remove_cartorder_cart_and_more'),
        ('api', '0048_remove_order_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.checkoutorder'),
        ),
    ]
