# Generated by Django 4.2.3 on 2023-07-26 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_remove_ordergroup_subscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='order_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='api.ordergroup'),
        ),
    ]
