# Generated by Django 4.2.13 on 2024-09-10 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_order_checkout_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transaction'},
        ),
        migrations.AlterModelOptions(
            name='orderdisposalticket',
            options={'verbose_name': 'Transaction Disposal Ticket', 'verbose_name_plural': 'Transaction Disposal Tickets'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitem',
            options={'verbose_name': 'Transaction Line Item', 'verbose_name_plural': 'Transaction Line Items'},
        ),
        migrations.AlterModelOptions(
            name='orderlineitemtype',
            options={'verbose_name': 'Transaction Line Item Type', 'verbose_name_plural': 'Transaction Line Item Types'},
        ),
    ]
