# Generated by Django 4.2.3 on 2023-07-26 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_subscription_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproduct',
            name='product',
            field=models.ForeignKey(default='fac96db2-396d-4cd6-bf34-1c84d07e068f', on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='api.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerproduct',
            name='seller',
            field=models.ForeignKey(default='dd7afca3-e994-468a-af50-c0a631234b28', on_delete=django.db.models.deletion.CASCADE, related_name='seller_products', to='api.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_location',
            field=models.ForeignKey(default='ec008246-10d8-4af3-b53b-0a8dc67c38dc', on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_product', to='api.sellerlocation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_product',
            field=models.ForeignKey(default='ffd3cc2c-b4b9-4d51-a7bc-6bef07f87231', on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_product', to='api.sellerproduct'),
            preserve_default=False,
        ),
    ]
