# Generated by Django 4.2.13 on 2024-09-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='backbill',
            field=models.BooleanField(default=False),
        ),
    ]
