# Generated by Django 4.2.3 on 2023-07-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_sellerproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
