# Generated by Django 4.2.3 on 2023-07-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_user_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='tonnage_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
