# Generated by Django 4.2.13 on 2024-09-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_orderlineitem_backbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
