# Generated by Django 4.1 on 2024-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0053_orderlineitem_tax"),
    ]

    operations = [
        migrations.AddField(
            model_name="mainproductinfo",
            name="description",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
