# Generated by Django 4.2.3 on 2023-08-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_usergroup_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='share_code',
            field=models.CharField(default='ABC123', max_length=6),
            preserve_default=False,
        ),
    ]
