# Generated by Django 4.2.13 on 2024-09-20 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_mainproductinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='account_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='account_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='apollo_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='stage',
            field=models.CharField(blank=True, choices=[('LEAD', 'Active Opportunity'), ('CUSTOMER', 'Current Client'), ('CHURNED', 'Churned Customer'), ('DEAD_LEAD', 'Dead opportunity')], max_length=20, null=True),
        ),
    ]
