# Generated by Django 4.2.13 on 2024-09-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_usergroup_account_owner_usergroup_apollo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apollo_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='apollo_user_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stage',
            field=models.CharField(blank=True, choices=[('CREATED', 'User Created'), ('ACTIVE', 'Active User'), ('CHURNED', 'Churned User'), ('DEAD', 'Dead Opportunity')], max_length=20, null=True),
        ),
    ]
