# Generated by Django 4.1 on 2024-10-19 18:14

import common.utils.file_field.get_uuid_file_path
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0056_user_apollo_id_user_apollo_user_id_user_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordergroup",
            name="agreement",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=common.utils.file_field.get_uuid_file_path.get_uuid_file_path,
            ),
        ),
    ]
