# Generated by Django 4.2.3 on 2023-08-09 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_useraddress_user_alter_usergroup_share_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='seller',
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.seller'),
        ),
        migrations.CreateModel(
            name='UserSellerLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('seller_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sellerlocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
