# Generated by Django 4.1 on 2024-10-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0058_ordergroup_agreement_signed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
