# Generated by Django 4.2.3 on 2023-08-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_useraddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersellerreview',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
