# Generated by Django 4.2.3 on 2023-08-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_usersellerreview_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproductsellerlocationmaterialwastetype',
            name='tonnage_included',
            field=models.IntegerField(default=0),
        ),
    ]
