# Generated by Django 4.2.13 on 2024-11-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_mainproductcategorygroup_mainproductcategory_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
