# Generated by Django 4.2.3 on 2023-08-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_sellerproductsellerlocationmaterialwastetype_tonnage_included'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerproductsellerlocationmaterial',
            name='tonnage_included',
        ),
        migrations.AddField(
            model_name='sellerproduct',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
