# Generated by Django 4.2.13 on 2024-11-25 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_seller_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rating', models.BooleanField(choices=[(0, 'Thumbs Down'), (1, 'Thumbs Up')], help_text='How was your experience?', verbose_name='Overall Experience Rating')),
                ('professionalism', models.IntegerField(blank=True, choices=[(1, 'Unacceptable'), (2, 'Unsatisfactory'), (3, 'Neutral'), (4, 'Satisfactory'), (5, 'Exceptional')], help_text="How was the seller's professionalism?", null=True)),
                ('communication', models.IntegerField(blank=True, choices=[(1, 'Unacceptable'), (2, 'Unsatisfactory'), (3, 'Neutral'), (4, 'Satisfactory'), (5, 'Exceptional')], help_text="How was the seller's communication?", null=True)),
                ('pricing', models.IntegerField(blank=True, choices=[(1, 'Unacceptable'), (2, 'Unsatisfactory'), (3, 'Neutral'), (4, 'Satisfactory'), (5, 'Exceptional')], help_text="How was the seller's pricing?", null=True)),
                ('timeliness', models.IntegerField(blank=True, choices=[(1, 'Unacceptable'), (2, 'Unsatisfactory'), (3, 'Neutral'), (4, 'Satisfactory'), (5, 'Exceptional')], help_text="How was the seller's timeliness?", null=True)),
                ('comment', models.TextField(blank=True, help_text='Please provide any additional feedback.', max_length=500, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction Review',
                'verbose_name_plural': 'Transaction Reviews',
            },
        ),
        migrations.DeleteModel(
            name='UserSellerReview',
        ),
    ]
