# Generated by Django 4.2.3 on 2023-08-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_mainproductwastetype_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderlineitem',
            old_name='price',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='is_flat_rate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlineitemtype',
            name='units',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='orderlineitem',
            unique_together={('order', 'order_line_item_type')},
        ),
    ]
