# Generated by Django 4.2.3 on 2023-08-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_rename_price_orderlineitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitemtype',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
