# Generated by Django 4.2.13 on 2024-11-27 14:19

import api.models.seller.seller_location
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_orderreview_delete_usersellerreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlocation',
            name='announcement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='lead_time_hrs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='live_menu_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='location_logo_image',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.seller.seller_location.SellerLocation.get_file_path),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='open_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY'), ('SUNDAY', 'SUNDAY')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
