# Generated by Django 4.2.13 on 2024-12-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_sellerlocation_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=models.CharField(choices=[('SALES', 'Downstream Sales Rep'), ('GOOGLE', 'Google Search'), ('SOCIAL_MEDIA', 'Social Media (e.g., Facebook, Instagram, LinkedIn)'), ('SUPPLIER', 'Referral from a Supplier'), ('WORD_OF_MOUTH', 'Word of Mouth'), ('ONLINE_AD', 'Online Ad (e.g., Google Ads, Facebook Ads)'), ('EVENT', 'Trade Show or Industry Event'), ('EMAIL', 'Email Campaign'), ('WEBSITE', 'Industry Directory or Website'), ('COWORKER', 'Referral from Co-Worker'), ('OTHER', 'Other'), ('', 'Unknown')], default='', max_length=50, verbose_name='How did you hear about us?'),
        ),
    ]
