# Generated by Django 4.2.3 on 2023-08-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_orderlineitemtype_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderlineitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
