# Generated by Django 4.2.3 on 2023-09-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_alter_orderlineitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='lead_time_hrs',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True),
        ),
    ]
