# Generated by Django 4.2.13 on 2024-12-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_user_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
