# Generated by Django 4.2.3 on 2023-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_seller_lead_time_hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
