# Generated by Django 4.2.13 on 2024-12-03 13:39

import api.models.seller.seller
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_seller_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.seller.seller.Seller.get_file_path),
        ),
    ]
