# Generated by Django 4.2.13 on 2024-12-03 17:28

import common.utils.get_file_path
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_seller_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path)),
                ('sort', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Industries',
                'ordering': ['sort', 'name'],
            },
        ),
        migrations.AddField(
            model_name='usergroup',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_groups', to='api.industry'),
        ),
    ]
