# Generated by Django 4.2.3 on 2023-09-15 02:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_alter_ordergroup_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('supplier_invoice_id', models.CharField(max_length=255)),
                ('supplier_invoice_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('ESCALATED', 'Escalated'), ('ERROR', 'Error'), ('READY_FOR_PAYOUT', 'Ready for Payout'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('melio_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_payout_id', models.CharField(blank=True, max_length=255, null=True)),
                ('orders', models.ManyToManyField(to='api.order')),
                ('seller_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
