# Generated by Django 4.2.13 on 2024-12-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_industry_usergroup_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='estimated_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
