# Generated by Django 4.2.3 on 2023-09-16 13:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='invoice_file',
            field=models.FileField(blank=True, null=True),
        ),
    ]
