# Generated by Django 4.2.13 on 2024-12-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_ordergroup_estimated_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='equipment_coi_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
