# Generated by Django 4.2.3 on 2023-09-18 22:17

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_payout_invoice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerInvoicePayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to=api.models.SellerInvoicePayable.get_file_path)),
                ('supplier_invoice_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('ESCALATED', 'Escalated'), ('ERROR', 'Error'), ('READY_FOR_PAYOUT', 'Ready for Payout'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='payout',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='seller_location',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='supplier_invoice_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='supplier_invoice_total',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SellerInvoicePayableLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('seller_invoice_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sellerinvoicepayable')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sellerinvoicepayable',
            name='seller_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.sellerlocation'),
        ),
        migrations.CreateModel(
            name='PayoutLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
