# Generated by Django 4.2.3 on 2023-09-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_sellerinvoicepayable_remove_payout_invoice_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='stripe_payout_id',
            new_name='stripe_transfer_id',
        ),
        migrations.RemoveField(
            model_name='payout',
            name='stripe_transaction_id',
        ),
    ]
