# Generated by Django 4.2.13 on 2024-12-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_usergroup_equipment_coi_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='equipment_coi_expiration_date',
            new_name='RPP_COI_Exp_Date',
        ),
    ]
