# Generated by Django 4.2.13 on 2024-12-23 17:05

import common.utils.get_file_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_rename_equipment_coi_expiration_date_usergroup_rpp_coi_exp_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to=common.utils.get_file_path.get_file_path)),
                ('sort', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.mainproduct')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
