# Generated by Django 4.2.3 on 2023-09-25 14:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_rename_stripe_payout_id_payout_stripe_transfer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.useraddress')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='payoutlineitem',
            name='payout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_line_items', to='api.payout'),
        ),
        migrations.CreateModel(
            name='PaymentLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('stripe_invoice_line_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.payment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
