# Generated by Django 4.2.13 on 2024-12-26 21:26

import common.utils.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_mainproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproductcategorygroup',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path),
        ),
    ]
