# Generated by Django 4.2.3 on 2023-09-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_order_end_date_alter_order_service_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, choices=[('Delivery', 'Delivery'), ('Automatic Renewal', 'Automatic Renewal'), ('Swap', 'Swap'), ('Empty and Return', 'Empty and Return'), ('Trip Charge/Dry Run', 'Trip Charge/Dry Run'), ('Removal', 'Removal'), ('On Demand', 'On Demand'), ('Other', 'Other')], max_length=255, null=True),
        ),
    ]
