# Generated by Django 4.2.17 on 2024-12-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_mainproductcategorygroup_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproductcategory',
            name='industry',
            field=models.ManyToManyField(blank=True, related_name='main_product_categories', to='api.industry'),
        ),
    ]
