# Generated by Django 4.2.13 on 2024-12-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_mainproductcategory_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductcategory',
            name='industry',
            field=models.ManyToManyField(blank=True, null=True, related_name='industry', to='api.industry'),
        ),
    ]
