# Generated by Django 4.2.3 on 2023-10-03 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='service_recurring_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.servicerecurringfrequency'),
        ),
    ]
