# Generated by Django 4.2.13 on 2024-12-27 16:02

import common.utils.get_file_path
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_mainproductcategory_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField(help_text='Short text segment that will be displayed on the advertisement.', max_length=50)),
                ('image', models.ImageField(upload_to=common.utils.get_file_path.get_file_path)),
                ('is_active', models.BooleanField(default=True)),
                ('sort', models.IntegerField(default=0)),
                ('background_color', models.CharField(help_text='Hex color code.', max_length=7)),
                ('text_color', models.CharField(default='#000000', help_text='Hex color code.', max_length=7)),
                ('object_type', models.CharField(choices=[('main_product_category', 'Product Category')], default='main_product_category')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('main_product_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mainproductcategory')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort'],
            },
        ),
    ]
