# Generated by Django 4.2.13 on 2024-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_advertisement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='service_radius',
            field=models.DecimalField(decimal_places=0, default=40, max_digits=18),
        ),
    ]
