# Generated by Django 4.2.3 on 2023-10-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_ordergroup_service_recurring_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductcategory',
            name='sort',
            field=models.IntegerField(),
        ),
    ]
