# Generated by Django 4.2.3 on 2023-10-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_mainproductcategory_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='sort',
            field=models.IntegerField(),
        ),
    ]
