# Generated by Django 4.2.13 on 2024-12-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_alter_sellerproductsellerlocation_service_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='delivered_to_street',
            field=models.BooleanField(default=False),
        ),
    ]
