# Generated by Django 4.2.3 on 2023-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_alter_mainproduct_sort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproduct',
            name='cubic_yards',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
