# Generated by Django 4.2.13 on 2024-12-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_ordergroup_delivered_to_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproduct',
            name='allows_pick_up',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sellerproductsellerlocation',
            name='allows_pick_up',
            field=models.BooleanField(default=True),
        ),
    ]
