# Generated by Django 4.2.17 on 2025-01-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0004_alter_paymentmethod_user_group'),
        ('api', '0080_mainproduct_allows_pick_up_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='default_payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment_methods.paymentmethod'),
        ),
    ]
