# Generated by Django 4.2.3 on 2023-10-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_mainproduct_cubic_yards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.ordergroup'),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_line_items', to='api.order'),
        ),
    ]
