# Generated by Django 4.2.3 on 2023-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_alter_order_order_group_alter_orderlineitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='take_rate',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=18),
        ),
    ]
