# Generated by Django 4.2.13 on 2025-01-06 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0082_ordergroup_is_delivery"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderTransferFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Transfer Fee",
                "verbose_name_plural": "Transaction Transfer Fees",
            },
        ),
        migrations.CreateModel(
            name="OrderPermitFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Permit Fee",
                "verbose_name_plural": "Transaction Permit Fees",
            },
        ),
        migrations.CreateModel(
            name="OrderMaterialFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Material Fee",
                "verbose_name_plural": "Transaction Material Fees",
            },
        ),
        migrations.CreateModel(
            name="OrderMaintenanceFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Maintenance Fee",
                "verbose_name_plural": "Transaction Maintenance Fees",
            },
        ),
        migrations.CreateModel(
            name="OrderInsurance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Insurance",
                "verbose_name_plural": "Transaction Insurance",
            },
        ),
        migrations.CreateModel(
            name="OrderDamageFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Damage Fee",
                "verbose_name_plural": "Transaction Damage Fees",
            },
        ),
        migrations.CreateModel(
            name="OrderAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=18)),
                (
                    "customer_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the customer is charged for this item (ex: 25.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "seller_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The rate the seller is paid for this item (ex: 20.00)",
                        max_digits=18,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "stripe_invoice_line_item_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("paid", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.order"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction Adjustment",
                "verbose_name_plural": "Transaction Adjustments",
            },
        ),
    ]
