# Generated by Django 4.2.3 on 2023-10-31 15:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_ordergroup_take_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGroupService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('miles', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='api.ordergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGroupRental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('included_days', models.IntegerField(default=0)),
                ('price_per_day_included', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('price_per_day_additional', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='api.ordergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderGroupMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('price_per_ton', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('tonnage_included', models.IntegerField(default=0)),
                ('order_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='material', to='api.ordergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
