# Generated by Django 4.2.3 on 2023-11-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_ordergroupservice_ordergrouprental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='compliance_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('REQUESTED', 'Requested'), ('IN-PROGRESS', 'In-Progress'), ('NEEDS_REVIEW', 'Needs Review'), ('APPROVED', 'Approved')], default='NOT_REQUIRED', max_length=20),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='credit_line_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
