# Generated by Django 4.2.13 on 2025-01-07 21:55

import api.models.main_product.main_product_category
import common.utils.get_file_path
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_ordertransferfee_orderpermitfee_ordermaterialfee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainproductcategory',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=common.utils.get_file_path.get_file_path, validators=[api.models.main_product.main_product_category.MainProductCategory.validate_file_extension]),
        ),
    ]
