# Generated by Django 4.2.13 on 2025-01-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_mainproductcategory_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproductcategory',
            name='image',
        ),
    ]
