# Generated by Django 4.2.3 on 2023-11-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_usergroup_compliance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=18),
        ),
    ]
