# Generated by Django 4.2.13 on 2025-01-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_mainproductcategory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainproductcategory',
            old_name='image2',
            new_name='image',
        ),
    ]
