# Generated by Django 4.2.3 on 2023-11-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_alter_sellerlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='seller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.seller'),
        ),
    ]
