# Generated by Django 4.2.13 on 2025-01-10 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("permits", "0001_initial"),
        ("api", "0086_rename_image2_mainproductcategory_image"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="orderpermitfee",
            name="permit",
            field=models.ForeignKey(
                default="41175847-1ea0-41a6-b81f-8374ce038b39",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_permit_fees",
                to="permits.permit",
            ),
            preserve_default=False,
        ),
    ]
