# Generated by Django 4.2.3 on 2023-11-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_alter_usergroup_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergroup',
            name='delivery_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ordergroup',
            name='removal_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='productaddonchoice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_add_on_choices', to='api.product'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocationmaterialwastetype',
            name='seller_product_seller_location_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waste_types', to='api.sellerproductsellerlocationmaterial'),
        ),
    ]
