# Generated by Django 4.2.3 on 2023-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_ordergroup_delivery_fee_ordergroup_removal_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroup',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='removal_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
