# Generated by Django 4.2.17 on 2025-01-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
