# Generated by Django 4.2.3 on 2023-11-15 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_alter_ordergroup_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payout',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payout',
            name='order',
            field=models.ForeignKey(default='9190a1fd-9bb4-4fac-ac48-dc9a5cb2287c', on_delete=django.db.models.deletion.CASCADE, to='api.order'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PayoutLineItem',
        ),
    ]
