# Generated by Django 4.2.3 on 2023-11-15 14:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_payout_amount_payout_description_payout_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlocation',
            name='auto_coi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.SellerLocation.get_file_path),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='auto_coi_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='auto_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='gl_coi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.SellerLocation.get_file_path),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='gl_coi_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='gl_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='w9',
            field=models.FileField(blank=True, null=True, upload_to=api.models.SellerLocation.get_file_path),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='workers_comp_coi',
            field=models.FileField(blank=True, null=True, upload_to=api.models.SellerLocation.get_file_path),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='workers_comp_coi_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellerlocation',
            name='workers_comp_limit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
    ]
