# Generated by Django 4.2.3 on 2023-11-22 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_sellerlocation_auto_coi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlocation',
            name='payee_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='SellerLocationMailingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('street', models.TextField(blank=True, null=True)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('seller_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.sellerlocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
