# Generated by Django 4.2.13 on 2025-01-23 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0091_bundle_ordergroup_bundle"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderadjustment",
            name="order_line_item_type",
            field=models.ForeignKey(
                default="71ef588f-8454-4914-ae81-a524dcb483e9",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_adjustments",
                to="api.orderlineitemtype",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderadjustment",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderdamagefee",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderinsurance",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ordermaintenancefee",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ordermaterialfee",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="orderpermitfee",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ordertransferfee",
            name="quantity",
            field=models.IntegerField(),
        ),
    ]
