# Generated by Django 4.2.13 on 2025-01-22 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_bundle_ordergroup_bundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='removal_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bundle'),
        ),
    ]
