# Generated by Django 4.2.13 on 2025-01-28 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0092_orderadjustment_order_line_item_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderinsurance",
            options={
                "verbose_name": "Transaction Protection Plan",
                "verbose_name_plural": "Transaction Protection Plans",
            },
        ),
        migrations.AddField(
            model_name="sellerlocation",
            name="payout_delay",
            field=models.IntegerField(
                default=14,
                help_text="Number of days to delay payout after an invoice is received.",
            ),
        ),
    ]
