# Generated by Django 4.2.13 on 2025-01-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_orderadjustment_order_line_item_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bundle',
            new_name='FreightBundle',
        ),
        migrations.AlterModelOptions(
            name='orderinsurance',
            options={'verbose_name': 'Transaction Protection Plan', 'verbose_name_plural': 'Transaction Protection Plans'},
        ),
        migrations.RenameField(
            model_name='ordergroup',
            old_name='bundle',
            new_name='freight_bundle',
        ),
    ]
