# Generated by Django 4.2.3 on 2023-11-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_sellerlocationmailingaddress_seller_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payout',
            old_name='melio_payout_id',
            new_name='checkbook_payout_id',
        ),
    ]
