# Generated by Django 4.2.13 on 2025-01-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_alter_orderinsurance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainproductinfo',
            name='sort',
            field=models.IntegerField(default=0),
        ),
    ]
