# Generated by Django 4.2.13 on 2025-01-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0094_alter_mainproductinfo_description_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bundle',
            new_name='FreightBundle',
        ),
        migrations.RenameField(
            model_name='ordergroup',
            old_name='bundle',
            new_name='freight_bundle',
        ),
    ]
