# Generated by Django 4.2.3 on 2023-12-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0095_seller_order_email_seller_order_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='paymentlineitem',
            name='payment',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='stripe_invoice_line_item_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sellerlocation',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_locations', to='api.seller'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_products', to='api.sellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_location_seller_products', to='api.sellerproduct'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentLineItem',
        ),
    ]
