# Generated by Django 4.2.13 on 2025-02-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0096_useraddress_tax_exempt_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerlocation",
            name="ein",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
