# Generated by Django 3.2.20 on 2023-12-11 16:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_orderlineitemtype_stripe_tax_code_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='api.usergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
