# Generated by Django 3.2.20 on 2023-12-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_usergroupbilling'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='tax_exempt_status',
            field=models.CharField(choices=[('none', 'None'), ('exempt', 'Exempt'), ('reverse', 'Reverse')], default='none', max_length=20),
        ),
    ]
