# Generated by Django 4.2.17 on 2025-02-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_industry_slug_mainproduct_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True, unique=True),
        ),
    ]
