# Generated by Django 4.2.13 on 2025-02-13 16:44

import api.models.order.order_group_attachment
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_user_stripe_id_usergroup_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergroupattachment',
            name='file',
            field=models.FileField(upload_to=api.models.order.order_group_attachment.OrderGroupAttachment.get_file_path, validators=[api.models.order.order_group_attachment.OrderGroupAttachment.validate_file_extension]),
        ),
        migrations.CreateModel(
            name='OrderGroupNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='Note Text')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('order_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='api.ordergroup')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Note',
                'verbose_name_plural': 'Booking Notes',
            },
        ),
    ]
