# Generated by Django 3.2.20 on 2023-12-14 16:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_usergroup_tax_exempt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroupLegal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('doing_business_as', models.CharField(blank=True, max_length=255, null=True)),
                ('structure', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('llc', 'Llc'), ('s_corp', 'S Corp'), ('c_corp', 'C Corp'), ('other', 'Other')], max_length=20)),
                ('industry', models.CharField(choices=[('property_management', 'Property Management'), ('construction', 'Construction'), ('manufacturing', 'Manufacturing'), ('waste_collection', 'Waste Collection'), ('other', 'Other')], max_length=20)),
                ('year_founded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('street', models.TextField()),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=80)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18)),
                ('user_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legal', to='api.usergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserGroupCreditApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('requested_credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_applications', to='api.usergroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
