# Generated by Django 4.2.13 on 2025-02-13 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_ordergroupattachment_file_ordergroupnote'),
        ('api', '0100_ordergroupservicetimesperweek_one_every_other_week_and_more'),
    ]

    operations = [
    ]
