# Generated by Django 4.2.17 on 2025-02-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_merge_20250213_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermaterialfee',
            name='customer_rate_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate the customer is charged for this item (ex: 25.00)', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ordermaterialfee',
            name='quantity_decimal',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The quantity of the material fee.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='ordermaterialfee',
            name='seller_rate_decimal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate the seller is paid for this item (ex: 20.00)', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='customer_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate the customer is charged for this item (ex: 25.00)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='seller_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The rate the seller is paid for this item (ex: 20.00)', max_digits=18),
        ),
    ]
