# Generated by Django 3.2.20 on 2023-12-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_remove_order_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
