# Generated by Django 4.2.17 on 2025-02-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_ordermaterialfee_customer_rate_decimal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='customer_rate_decimal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The rate the customer is charged for this item (ex: 25.00)', max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='quantity_decimal',
            field=models.DecimalField(decimal_places=4, default=0, help_text='The quantity of the material fee.', max_digits=18),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermaterialfee',
            name='seller_rate_decimal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The rate the seller is paid for this item (ex: 20.00)', max_digits=18),
            preserve_default=False,
        ),
    ]
