# Generated by Django 3.2.20 on 2023-12-27 15:43

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_orderlineitem_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdisposalticket',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=api.models.OrderDisposalTicket.get_file_path),
        ),
        migrations.AlterField(
            model_name='orderdisposalticket',
            name='disposal_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.disposallocation'),
        ),
    ]
