# Generated by Django 3.2.20 on 2024-01-03 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_auto_20231227_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='api.order'),
        ),
        migrations.AlterField(
            model_name='sellerinvoicepayablelineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice_payable_line_items', to='api.order'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='stripe_customer_id',
            field=models.CharField(max_length=255),
        ),
    ]
