# Generated by Django 3.2.20 on 2024-01-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_auto_20240103_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='stripe_customer_id',
        ),
        migrations.RemoveField(
            model_name='usergroup',
            name='stripe_customer_id',
        ),
    ]
