# Generated by Django 3.2.20 on 2024-01-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_auto_20240103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
