# Generated by Django 3.2.20 on 2024-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_alter_useraddress_stripe_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=20, help_text='Enter as a percentage without the percent symbol (ex: 25.00)', max_digits=18),
        ),
    ]
