# Generated by Django 3.2.20 on 2024-01-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0108_alter_orderlineitem_platform_fee_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerlocation',
            name='sends_invoices',
            field=models.BooleanField(default=False),
        ),
    ]
