# Generated by Django 3.2.20 on 2024-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0109_sellerlocation_sends_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='access_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='invoice_frequency',
            field=models.IntegerField(choices=[(0, 'Immediately'), (7, 'Weekly'), (14, 'Bi-Weekly'), (30, 'Monthly')], default=0),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='net_terms',
            field=models.IntegerField(choices=[(0, 'Immediately'), (14, 'Net 14'), (30, 'Net 30'), (45, 'Net 45'), (60, 'Net 60')], default=0),
        ),
    ]
