# Generated by Django 3.2.20 on 2024-01-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0110_auto_20240118_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=18),
        ),
    ]
