# Generated by Django 3.2.20 on 2024-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0111_auto_20240131_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='invoice_day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
