# Generated by Django 3.2.20 on 2024-02-02 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0112_usergroup_invoice_day_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='invoice_frequency',
            field=models.IntegerField(blank=True, choices=[(0, 'Immediately'), (7, 'Weekly'), (14, 'Bi-Weekly'), (30, 'Monthly')], default=0, null=True),
        ),
    ]
