# Generated by Django 3.2.20 on 2024-02-11 07:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_alter_usergroup_invoice_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinvoicepayable',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
