# Generated by Django 3.2.20 on 2024-02-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_remove_order_service_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='included_weight_tons',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payout_processing_error_comment',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salesforce_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='stripe_invoice_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier_payout_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='suppplier_payout_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='unit_price',
        ),
    ]
