# Generated by Django 3.2.20 on 2024-02-20 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_auto_20240212_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='invoice_at_project_completion',
            field=models.BooleanField(default=False, help_text='Send invoices when all OrderGroups in a project are completed.'),
        ),
        migrations.AlterField(
            model_name='mainproduct',
            name='main_product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_products', to='api.mainproductcategory'),
        ),
        migrations.AlterField(
            model_name='ordergroup',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_groups', to='api.useraddress'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.mainproduct'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product_seller_locations', to='api.sellerlocation'),
        ),
        migrations.AlterField(
            model_name='sellerproductsellerlocation',
            name='seller_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_product_seller_locations', to='api.sellerproduct'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to='api.usergroup'),
        ),
    ]
