# Generated by Django 4.1 on 2024-02-29 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0117_auto_20240220_1702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="api.usergroup",
            ),
        ),
        migrations.AlterField(
            model_name="useraddress",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
