# Generated by Django 4.1 on 2024-03-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payment_methods", "0001_initial"),
        ("api", "0118_alter_user_user_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraddress",
            name="default_payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment_methods.paymentmethod",
            ),
        ),
    ]
