# Generated by Django 4.2.3 on 2024-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_alter_user_user_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='intercom_id',
            field=models.CharField(blank=True, help_text='This is the company_id in Intercom.', max_length=255, null=True),
        ),
    ]
