# Generated by Django 4.2.3 on 2024-03-16 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_useraddress_default_payment_method'),
        ('api', '0119_usergroup_intercom_id'),
    ]

    operations = [
    ]
