# Generated by Django 4.2.3 on 2024-03-16 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_merge_20240316_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='intercom_id',
        ),
    ]
