# Generated by Django 4.2.3 on 2024-03-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0121_remove_usergroup_intercom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='intercom_id',
            field=models.CharField(blank=True, help_text='This is the company_id in Intercom.', max_length=255, null=True),
        ),
    ]
