# Generated by Django 4.1 on 2024-04-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0122_usergroup_intercom_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("BILLING", "Billing Manager"),
                    ("MEMBER", "Member"),
                ],
                default="ADMIN",
                max_length=255,
            ),
        ),
    ]
