# Generated by Django 4.2.3 on 2024-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0122_usergroup_intercom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='lob_check_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
