# Generated by Django 4.2.11 on 2024-04-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('APPROVAL', 'Approval'), ('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('IN-PROGRESS', 'In-Progress'), ('Awaiting Request', 'Awaiting Request'), ('CANCELLED', 'Cancelled'), ('COMPLETE', 'Complete')], default='PENDING', max_length=20),
        ),
    ]
