# Generated by Django 4.1 on 2024-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0123_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergroupcreditapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
