# Generated by Django 4.2.11 on 2024-04-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_alter_order_status'),
        ('api', '0124_usergroupcreditapplication_status'),
    ]

    operations = [
    ]
