# Generated by Django 4.1 on 2024-06-10 23:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="users",
        ),
    ]
