# Generated by Django 4.2.13 on 2025-01-02 18:30

import crm.models.lead
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0080_mainproduct_allows_pick_up_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('est_conversion_date', models.DateField(blank=True, default=crm.models.lead.get_default_est_conversion_date, null=True, verbose_name='Estimated Conversion Date')),
                ('type', models.CharField(choices=[('customer', 'Customer'), ('seller', 'Seller')], default='customer', max_length=25)),
                ('status', models.CharField(choices=[('sign_up', 'New Sign Up'), ('location', 'New Location Added'), ('manual', 'Manually Created/Reengagement'), ('converted', 'Converted'), ('interested', 'Interest Expressed/Nurturing'), ('junk', 'Junk')], default='manual', max_length=25)),
                ('lost_reason', models.CharField(blank=True, choices=[(None, 'N/A'), ('duplicate', 'Duplicate Lead'), ('invalid', 'Invalid Contact Information'), ('unqualified', 'Not a Buyer/Decision Maker'), ('uninterested', 'Uninterested'), ('junk', 'Junk/Spam/Bot'), ('expired', 'Conversion Date Passed'), ('other', 'Other')], max_length=25, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_leads', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_leads', to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.useraddress')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
