# Generated by Django 4.2.13 on 2025-01-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='est_value',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Estimated Value'),
        ),
    ]
