# Generated by Django 4.2.13 on 2024-09-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
