# Generated by Django 4.2.13 on 2024-09-09 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0003_paymentmethod_active_paymentmethod_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0048_remove_order_cart_order'),
        ('cart', '0002_alter_cartorder_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('pay_later', models.BooleanField(default=False)),
                ('is_stale', models.BooleanField(default=False)),
                ('quote', models.JSONField(blank=True, help_text='Quote json from get_quote_data.', null=True)),
                ('take_rate', models.DecimalField(decimal_places=2, default=30, help_text='Take rate is from OrderGroup.', max_digits=18)),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('seller_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('to_emails', models.CharField(blank=True, help_text='Comman separated emails to send quote to.', max_length=255, null=True)),
                ('subject', models.CharField(blank=True, help_text='Subject for the email.', max_length=255, null=True)),
                ('quote_expiration', models.DateTimeField(blank=True, null=True)),
                ('quote_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to='payment_methods.paymentmethod')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to='api.useraddress')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='user_address',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartOrder',
        ),
    ]
