# Generated by Django 4.2.13 on 2024-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_checkoutorder_remove_cartorder_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='code',
            field=models.CharField(blank=True, help_text='Unique code for the Transaction.', max_length=8, null=True, unique=True),
        ),
    ]
