# Generated by Django 4.2.13 on 2024-09-09 18:49

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkoutorder_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='quote',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Quote json from get_quote_data.', null=True),
        ),
    ]
