# Generated by Django 4.2.13 on 2024-09-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_checkoutorder_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutorder',
            name='estimated_taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
