# Generated by Django 4.2.13 on 2024-12-05 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_methods', '0004_alter_paymentmethod_user_group'),
        ('cart', '0006_checkoutorder_estimated_taxes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutorder',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_orders', to='payment_methods.paymentmethod'),
        ),
    ]
