# Generated by Django 4.2.17 on 2025-01-23 23:00

import common.utils.get_file_path
from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import notifications.models.push_notification
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_emailnotification_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('template_id', models.CharField(blank=True, help_text='The Customer IO template ID of the push notification.', max_length=64, null=True)),
                ('title', models.CharField(blank=True, help_text='The title of the push notification.', max_length=255, null=True)),
                ('message', models.TextField(blank=True, help_text='The message to be displayed in the push notification.', null=True)),
                ('image', models.ImageField(blank=True, help_text='The image to be displayed in the push notification. Max file size 1 MB.', null=True, upload_to=common.utils.get_file_path.get_file_path, validators=[notifications.models.push_notification.validate_image_file_size])),
                ('link', models.CharField(blank=True, help_text='A deeplink or URL to redirect the user to.', max_length=255, null=True)),
                ('custom_data', models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, help_text='Custom data to be sent with the push notification. Only supports string key value pairs.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PushNotificationTo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('send_error', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('push_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notification_tos', to='notifications.pushnotification')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
