# Generated by Django 4.2.13 on 2025-01-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_pushnotification_pushnotificationto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushnotification',
            options={'ordering': ['-sent_at']},
        ),
    ]
